
import { GoogleGenAI, Type } from "@google/genai";
import { AIGeneratedContent } from '../types';

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const rewriteSchema = {
  type: Type.OBJECT,
  properties: {
    title: {
      type: Type.STRING,
      description: 'Makale için kısa, ilgi çekici ve SEO dostu bir Türkçe başlık.',
    },
    body: {
      type: Type.STRING,
      description: 'Makalenin, arama motorları için optimize edilmiş ve kolay okunabilir, yaklaşık 3-4 paragraf uzunluğunda, Markdown formatında yeniden yazılmış Türkçe versiyonu.',
    },
    imagePrompt: {
      type: Type.STRING,
      description: 'A detailed, descriptive prompt in English for an AI image generator to create a photorealistic and relevant image for this news story. The prompt should describe the scene, subject, lighting, and style (e.g., "A photorealistic shot of a Boeing 787 Dreamliner soaring through a golden-hour sunset, with detailed clouds and contrails, high-resolution, dramatic lighting").',
    },
  },
  required: ['title', 'body', 'imagePrompt'],
};

export const processArticleWithAI = async (articleText: string): Promise<AIGeneratedContent> => {
  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-pro",
      contents: `Aşağıdaki havacılık haberi metnine dayanarak, lütfen yeni bir Türkçe başlık, SEO dostu yeniden yazılmış bir Türkçe gövde ve ayrıntılı bir resim istemi (image prompt) içeren bir JSON nesnesi oluşturun. Başlık ve gövde mutlaka Türkçe olmalıdır. Resim istemi (imagePrompt) İngilizce olmalıdır.

      Makale Metni:
      ---
      ${articleText}
      ---
      `,
      config: {
        responseMimeType: "application/json",
        responseSchema: rewriteSchema,
      },
    });

    const jsonText = response.text.trim();
    const parsedJson = JSON.parse(jsonText);
    
    // Validate the parsed JSON against the expected structure
    if (parsedJson.title && parsedJson.body && parsedJson.imagePrompt) {
        return parsedJson as AIGeneratedContent;
    } else {
        throw new Error("AI response is missing required fields.");
    }

  } catch (error) {
    console.error("Error processing article with AI:", error);
    throw new Error("Failed to process article. The AI model might be unavailable or the input was invalid.");
  }
};


export const generateImage = async (prompt: string): Promise<string> => {
    try {
        const response = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: prompt,
            config: {
              numberOfImages: 1,
              outputMimeType: 'image/jpeg',
              aspectRatio: '16:9',
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
            return `data:image/jpeg;base64,${base64ImageBytes}`;
        } else {
            throw new Error("No image was generated by the API.");
        }
    } catch (error) {
        console.error("Error generating image with AI:", error);
        throw new Error("Failed to generate image. The image model might be unavailable or the prompt was rejected.");
    }
};